export default {
  theme: {
    screens: {
      xs: '320px',
      sm: '640px',
      md: '760px',
      lg: '1024px',
      xl: '1280px',
      large: '1440px',
      '2xl': '1920px',
    },
    extend: {
      colors: {
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: '#202223',
          fixed: 'var(--utility-status04-70)',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          container: 'var(--secondary-container)',
        },
        on: {
          primary: 'var(--on-primary)',
          secondary: 'var(--on-secondary)',
          'secondary-container': 'var(--on-secondary-container)',
          surface: 'var(--on-surface)',
          'surface-variant': 'var(--on-surface-variant)',
          error: 'var(--on-error)',
          'error-container': 'var(--on-error-container)',
        },
        outline: {
          DEFAULT: 'var(--outline)',
          variant: 'var(--outline-variant)',
        },
        surface: {
          DEFAULT: 'var(--surface)',
          bold: 'var(--surface-bold)',
          subtlest: 'var(--surface-subtlest)',
          normal: 'var(--surface-normal)',
          variant: 'var(--surface-variant)',
          'variant-99': 'var(--surface-variant-99)',
          'container-low': 'var(--surface-container-low)',
          'container-high': 'var(--surface-container-high)',
          'create-bg': 'var(--surface-create-bg)',
          bright: 'var(--surface-bright)',

          // new，以前的代码中使用到了 surface-DEFAULT，因此新定义一个 surface-default 值避免冲突，后续要移除 surface-DEFAULT 值
          default: 'var(--surface-default)',
          subtle: 'var(--surface-subtle)',
          hovered: 'var(--surface-hovered)',
          'hoverd-static': 'var(--surface-hovered-static)',
          pressed: 'var(--surface-pressed)',
          'pressed-static': 'var(--surface-pressed-static)',
          special: 'var(--surface-container-special-default)',
          disabled: 'var(--surface-disabled)',
          'disabled-static': 'var(--surface-disabled-static)',
          'search-field': 'var(--surface-search-field)',
          inverse: 'var(--surface-inverse)',
          accent: {
            green: {
              subtle: 'var(--surface-accent-green-subtle)',
              subtler: 'var(--surface-accent-green-subtler)',
              subtlest: 'var(--surface-accent-green-subtlest)',
              bolder: 'var(--surface-accent-green-bolder)',
            },
            aqua: {
              subtle: 'var(--surface-accent-aqua-subtle)',
              subtler: 'var(--surface-accent-aqua-subtler)',
              subtlest: 'var(--surface-accent-aqua-subtlest)',
              bolder: 'var(--surface-accent-aqua-bolder)',
            },
            blue: {
              subtle: 'var(--surface-accent-blue-subtle)',
              subtler: 'var(--surface-accent-blue-subtler)',
              subtlest: 'var(--surface-accent-blue-subtlest)',
              bolder: 'var(--surface-accent-blue-bolder)',
            },
            yellow: {
              subtle: 'var(--surface-accent-yellow-subtle)',
              subtler: 'var(--surface-accent-yellow-subtler)',
              subtlest: 'var(--surface-accent-yellow-subtlest)',
              bolder: 'var(--surface-accent-yellow-bolder)',
            },
            red: {
              subtle: 'var(--surface-accent-red-subtle)',
              subtler: 'var(--surface-accent-red-subtler)',
              subtlest: 'var(--surface-accent-red-subtlest)',
              bolder: 'var(--surface-accent-red-bolder)',
            },
            gray: {
              subtle: 'var(--surface-accent-gray-subtle)',
              subtler: 'var(--surface-accent-gray-subtler)',
              subtlest: 'var(--surface-accent-gray-subtlest)',
              bolder: 'var(--surface-accent-gray-bolder)',
            },
          },
          primary: {
            default: 'var(--surface-primary-default)',
            hovered: 'var(--surface-primary-hovered)',
            pressed: 'var(--surface-primary-pressed)',
            subtle: {
              default: 'var(--surface-primary-subtle-default)',
              hovered: 'var(--surface-primary-subtle-hovered)',
              pressed: 'var(--surface-primary-subtle-pressed)',
            },
          },
          container: {
            DEFAULT: 'var(--surface-container)',
            default: 'var(--surface-container-default)',
            hovered: 'var(--surface-container-hovered)',
            pressed: 'var(--surface-container-pressed)',
            selected: {
              default: 'var(--surface-container-selected-default)',
              hovered: 'var(--surface-container-selected-hovered)',
              pressed: 'var(--surface-container-selected-pressed)',
            },
          },
          warning: {
            default: 'var(--surface-warning-default)',
            hovered: 'var(--surface-warning-hovered)',
            pressed: 'var(--surface-warning-pressed)',
            subtle: {
              default: 'var(--surface-warning-subtle-default)',
              hovered: 'var(--surface-warning-subtle-hovered)',
              pressed: 'var(--surface-warning-subtle-pressed)',
            },
          },
          success: {
            default: 'var(--surface-success-default)',
            hovered: 'var(--surface-success-hovered)',
            pressed: 'var(--surface-success-pressed)',
            subtle: {
              default: 'var(--surface-success-subtle-default)',
              hovered: 'var(--surface-success-subtle-hovered)',
              pressed: 'var(--surface-success-subtle-pressed)',
            },
          },
          critical: {
            default: 'var(--surface-critical-default)',
            hovered: 'var(--surface-critical-hovered)',
            pressed: 'var(--surface-critical-pressed)',
            subtle: {
              default: 'var(--surface-critical-subtle-default)',
              hovered: 'var(--surface-critical-subtle-hovered)',
              pressed: 'var(--surface-critical-subtle-pressed)',
            },
          },
          info: {
            default: 'var(--surface-info-default)',
            hovered: 'var(--surface-info-hovered)',
            pressed: 'var(--surface-info-pressed)',
            subtle: {
              default: 'var(--surface-info-subtle-default)',
              hovered: 'var(--surface-info-subtle-hovered)',
              pressed: 'var(--surface-info-subtle-pressed)',
            },
          },
          lemon: {
            bold: 'var(--surface-lemon-bold)',
            default: 'var(--surface-lemon-default)',
            subtle: 'var(--surface-lemon-subtle)',
            subtlest: 'var(--surface-lemon-subtlest)',
          },
        },
        alpha: {
          mask: {
            desktop: 'var(--alpha-mask-desktop)',
            mobile: 'var(--alpha-mask-mobile)',
          },
        },
        opaque: {
          facetime: {
            white: 'var(--opaque-facetime-white)',
            black: 'var(--opaque-facetime-black)',
            static: 'var(--opaque-facetime-static)',
          },
          mask: {
            desktop: 'var(--opaque-mask-desktop)',
            mobile: 'var(--opaque-mask-mobile)',
          },
          5: 'var(--white-5)',
          10: 'var(--white-10)',
          20: 'var(--white-20)',
          30: 'var(--white-30)',
          40: 'var(--white-40)',
          50: 'var(--white-50)',
          60: 'var(--white-60)',
          70: 'var(--white-70)',
          80: 'var(--white-80)',
          90: 'var(--white-90)',
          100: 'var(--white-100)',
        },
        inverse: {
          primary: 'var(--inverse-primary)',
          surface: 'var(--inverse-surface)',
        },
        error: {
          DEFAULT: 'var(--error)',
          container: 'var(--error-container)',
        },
        'white-opacity-95': 'rgba(255, 255, 255, 0.95)',
        'white-opacity-75': 'rgba(255, 255, 255, 0.75)',
        'black-opacity-95': 'rgba(0, 0, 0, 0.95)',
        'black-opacity-75': 'rgba(0, 0, 0, 0.75)',
        'task-black-opacity-75': 'rgba(39, 40, 44, 0.75)',
        'black-10': 'rgba(0, 0, 0, 0.10)',
        'white-10': 'rgba(255, 255, 255, 0.10)',
        neutral: {
          DEFAULT: 'var(--neutral)',
          10: 'var(--neutral-10)',
          20: 'var(--neutral-20)',
          30: 'var(--neutral-30)',
          40: 'var(--neutral-40)',
          50: 'var(--neutral-50)',
          60: 'var(--neutral-60)',
          70: 'var(--neutral-70)',
          75: 'var(--neutral-75)',
          80: 'var(--neutral-80)',
          85: 'var(--neutral-85)',
          90: 'var(--neutral-90)',
          95: 'var(--neutral-95)',
          99: 'var(--neutral-99)',
          variant: {
            DEFAULT: 'var(--neutral-variant)',
            5: 'var(--neutral-variant-5)',
            10: 'var(--neutral-variant-10)',
            15: 'var(--neutral-variant-15)',
            20: 'var(--neutral-variant-20)',
            30: 'var(--neutral-variant-30)',
            35: 'var(--neutral-variant-35)',
            40: 'var(--neutral-variant-40)',
            50: 'var(--neutral-variant-50)',
            60: 'var(--neutral-variant-60)',
            70: 'var(--neutral-variant-70)',
            80: 'var(--neutral-variant-80)',
            85: 'var(--neutral-variant-85)',
            88: 'var(--neutral-variant-88)',
            90: 'var(--neutral-variant-90)',
            95: 'var(--neutral-variant-95)',
            99: 'var(--neutral-variant-99)',
          },
          dark: {
            DEFAULT: 'var(--neutral-dark)',
            5: 'var(--neutral-dark-5)',
            10: 'var(--neutral-dark-10)',
            15: 'var(--neutral-dark-15)',
            20: 'var(--neutral-dark-20)',
            25: 'var(--neutral-dark-25)',
            30: 'var(--neutral-dark-30)',
            40: 'var(--neutral-dark-40)',
            50: 'var(--neutral-dark-50)',
            60: 'var(--neutral-dark-60)',
            70: 'var(--neutral-dark-70)',
            80: 'var(--neutral-dark-80)',
            85: 'var(--neutral-dark-85)',
            90: 'var(--neutral-dark-90)',
            95: 'var(--neutral-dark-95)',
            99: 'var(--neutral-dark-99)',
            special: {
              DEFAULT: 'var(--neutral-dark-special)',
              5: 'var(--neutral-dark-special-5)',
              10: 'var(--neutral-dark-special-10)',
              20: 'var(--neutral-dark-special-20)',
              30: 'var(--neutral-dark-special-30)',
              40: 'var(--neutral-dark-special-40)',
            },
          },
        },
        blue: {
          DEFAULT: 'var(--blue)',
          5: 'var(--blue-5)',
          10: 'var(--blue-10)',
          15: 'var(--blue-15)',
          20: 'var(--blue-20)',
          30: 'var(--blue-30)',
          40: 'var(--blue-40)',
          50: 'var(--blue-50)',
          60: 'var(--blue-60)',
          70: 'var(--blue-70)',
          80: 'var(--blue-80)',
          90: 'var(--blue-90)',
          95: 'var(--blue-95)',
          dark: {
            10: 'var(--blue-dark-10)',
            20: 'var(--blue-dark-20)',
            30: 'var(--blue-dark-30)',
            40: 'var(--blue-dark-40)',
            50: 'var(--blue-dark-50)',
          },
        },
        red: {
          DEFAULT: 'var(--red)',
          10: 'var(--red-10)',
          20: 'var(--red-20)',
          25: 'var(--red-25)',
          30: 'var(--red-30)',
          40: 'var(--red-40)',
          50: 'var(--red-50)',
          55: 'var(--red-55)',
          60: 'var(--red-60)',
          70: 'var(--red-70)',
          80: 'var(--red-80)',
          90: 'var(--red-90)',
          95: 'var(--red-95)',
          dark: {
            10: 'var(--red-dark-10)',
            20: 'var(--red-dark-20)',
            30: 'var(--red-dark-30)',
          },
        },
        yellow: {
          DEFAULT: 'var(--yellow)',
          5: 'var(--yellow-5)',
          10: 'var(--yellow-10)',
          15: 'var(--yellow-15)',
          20: 'var(--yellow-20)',
          30: 'var(--yellow-30)',
          35: 'var(--yellow-35)',
          40: 'var(--yellow-40)',
          50: 'var(--yellow-50)',
          60: 'var(--yellow-60)',
          70: 'var(--yellow-70)',
          80: 'var(--yellow-80)',
          90: 'var(--yellow-90)',
          95: 'var(--yellow-95)',
          dark: {
            10: 'var(--yellow-dark-10)',
            20: 'var(--yellow-dark-20)',
            30: 'var(--yellow-dark-30)',
          },
        },
        aqua: {
          DEFAULT: 'var(--aqua)',
          5: 'var(--aqua-5)',
          10: 'var(--aqua-10)',
          20: 'var(--aqua-20)',
          25: 'var(--aqua-25)',
          30: 'var(--aqua-30)',
          40: 'var(--aqua-40)',
          50: 'var(--aqua-50)',
          55: 'var(--aqua-55)',
          60: 'var(--aqua-60)',
          70: 'var(--aqua-70)',
          75: 'var(--aqua-75)',
          80: 'var(--aqua-80)',
          90: 'var(--aqua-90)',
          95: 'var(--aqua-95)',
          dark: {
            10: 'var(--aqua-dark-10)',
            20: 'var(--aqua-dark-20)',
            30: 'var(--aqua-dark-30)',
          },
        },
        green: {
          DEFAULT: 'var(--green)',
          10: 'var(--green-10)',
          20: 'var(--green-20)',
          25: 'var(--green-25)',
          30: 'var(--green-30)',
          40: 'var(--green-40)',
          50: 'var(--green-50)',
          60: 'var(--green-60)',
          70: 'var(--green-70)',
          80: 'var(--green-80)',
          90: 'var(--green-90)',
          95: 'var(--green-95)',
          dark: {
            10: 'var(--green-dark-10)',
            20: 'var(--green-dark-20)',
            30: 'var(--green-dark-30)',
          },
        },
        lemon: {
          DEFAULT: 'var(--lemon)',
          20: 'var(--lemon-20)',
          40: 'var(--lemon-40)',
          50: 'var(--lemon-50)',
          60: 'var(--lemon-60)',
          70: 'var(--lemon-70)',
          80: 'var(--lemon-80)',
          90: 'var(--lemon-90)',
        },
        utility: {
          status01: {
            20: 'var(--status01-20)',
            30: 'var(--status01-30)',
            40: 'var(--status01-40)',
            50: 'var(--status01-50)',
            60: 'var(--status01-60)',
            70: 'var(--status01-70)',
            80: 'var(--status01-80)',
            90: 'var(--status01-90)',
          },
          status02: {
            20: 'var(--status02-20)',
            30: 'var(--status02-30)',
            40: 'var(--status02-40)',
            50: 'var(--status02-50)',
            60: 'var(--status02-60)',
            70: 'var(--status02-70)',
            80: 'var(--status02-80)',
            90: 'var(--status02-90)',
          },
          status03: {
            20: 'var(--status03-20)',
            30: 'var(--status03-30)',
            40: 'var(--status03-40)',
            50: 'var(--status03-50)',
            60: 'var(--status03-60)',
            70: 'var(--status03-70)',
            80: 'var(--status03-80)',
            90: 'var(--status03-90)',
          },
          status04: {
            20: 'var(--status04-20)',
            30: 'var(--status04-30)',
            40: 'var(--status04-40)',
            50: 'var(--status04-50)',
            60: 'var(--status04-60)',
            70: 'var(--status04-70)',
            80: 'var(--status04-80)',
            90: 'var(--status04-90)',
          },
          status05: {
            20: 'var(--status05-20)',
            30: 'var(--status05-30)',
            40: 'var(--status05-40)',
            50: 'var(--status05-50)',
            60: 'var(--status05-60)',
            70: 'var(--status05-70)',
            80: 'var(--status05-80)',
            90: 'var(--status05-90)',
          },
        },
        icon: {
          DEFAULT: 'var(--icon)',
          subtle: 'var(--icon-subtle)',
          subtlest: 'var(--icon-subtlest)',
          disabled: 'var(--icon-disabled)',
          inverse: 'var(--icon-inverse)',
          static: 'var(--icon-static)',
          'static-black': 'var(--icon-static-black)',
          brand: 'var(--icon-brand)',
          critical: 'var(--icon-critical)',
          warning: 'var(--icon-warning)',
          success: 'var(--icon-success)',
        },
      },
      textColor: {
        default: 'var(--text)',
        subtle: 'var(--text-subtle)',
        subtler: 'var(--text-subtler)',
        subtlest: 'var(--text-subtlest)',
        disabled: 'var(--text-disabled)',
        inverse: 'var(--text-inverse)',
        'inverse-primary': 'var(--inverse-primary)',
        'inverse-surface': 'var(--inverse-surface)',
        static: 'var(--text-static)',
        'static-black': 'var(--text-static-black)',
        brand: 'var(--text-brand)',
        critical: 'var(--text-critical)',
        'critical-bolder': 'var(--text-critical-bolder)',
        warning: 'var(--text-warning)',
        'warning-bolder': 'var(--text-warning-bolder)',
        success: 'var(--text-success-default)',
        'success-bolder': 'var(--text-success-bolder)',
      },
      borderColor: {
        static: 'var(--border-static)',
        default: 'var(--border)',
        subtle: 'var(--border-subtle)',
        hovered: 'var(--border-hovered)',
        pressed: 'var(--border-pressed)',
        depressed: 'var(--border-depressed)',
        critical: 'var(--border-critical)',
        success: 'var(--border-success)',
        brand: 'var(--border-brand)',
        opaque: 'var(--border-opaque)',
        warning: 'var(--border-warning)',
        'warning-subtle': 'var(--border-warning-subtle)',
      },
      backgroundColor: {
        static: 'var(--surface-static)',
        'static-black': 'var(--surface-static-black)',
      },
      width: {
        4.5: '1.125rem',
        5.5: '1.375rem',
        18: '4.5rem',
        21: '5.25rem',
        30: '7.5rem',
      },
      height: {
        4.5: '1.125rem',
        5.5: '1.375rem',
        18: '4.5rem',
        21: '5.25rem',
        30: '7.5rem',
        dvh: '100dvh',
        workshop: 'calc(100dvh - 72px - 64px)',
      },
      gridTemplateColumns: {
        bot: 'repeat(3, minmax(300px, 1fr))',
        mbot: 'repeat(2, minmax(300px, 1fr))',
      },
      animation: {
        loading: 'loading 1s ease infinite',
        slideIn: 'slideIn .3s ease',
        slideIn1: 'slideIn1 .3s ease',
        move: 'move 1s linear infinite',
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
      keyframes: {
        loading: {
          '0%, 100%': { 'background-position': '0% 50%' },
          '50%': { 'background-position': '100% 50%' },
        },
        slideIn: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0px)' },
        },
        slideIn1: {
          '0%': {
            opacity: '0',
            transform: 'translateY(20px) translateX(-50%)',
            left: '50%',
          },
          '100%': {
            opacity: '1',
            transform: 'translateY(0px) translateX(-50%)',
            left: '50%',
          },
        },
        move: {
          '0%': {
            'background-position': '0px',
          },
          '100%': {
            'background-position': '50px',
          },
        },
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      fontFamily: {
        'mona-sans': ['var(--font-mona-sans)'],
        'pp-telegraf': ['var(--font-pp-telegraf)'],
        'roboto-mono': ['var(--font-roboto-mono)'],
        ppt: ['var(--font-ppt)'],
        'ppt-ultra-bold': ['var(--font-ppt-ultra-bold)'],
        mochiy: ['var(--font-mochiy)'],
        youyuan: ['var(--font-youyuan)'],
      },
      fontSize: {
        // 根据视觉稿增加 size 样式
        '2xs': ['0.625rem', '0.75rem'],
        '3xl': ['1.75rem', '2.25rem'],
        '4xl': ['1.875rem', '2.25rem'],
        '5xl': ['2.25rem', '2.5rem'],
        '6xl': ['3rem', '3.5rem'],
        '7xl': ['3.5rem', '4.25rem'],
      },
      boxShadow: {
        'surface-default': '0px 1px 2px 0px var(--shadow-surface-default)',
        'surface-bolder': '0px 3px 8px 0px var(--shadow-surface-bolder)',
        'button-basic': '0px 1px 0px 0px var(--shadow-button-basic)',
        'button-primary':
          '0px 1px 0px 0px var(--shadow-button-primary-1), 0px -1px 0px 0px var(--shadow-button-primary-2) inset',
        'button-primary1': '0px 1px 0px 0px var(--shadow-button-primary-1)',
        'button-primary2':
          '0px -1px 0px 0px var(--shadow-button-primary-2) inset',
        'button-pressed': '0px 2px 0px 0px var(--shadow-button-pressed) inset',
        'modal-default': '0px 0px 40px 0px var(--shadow-modal-default)',
        'modal-bolder':
          '0px 0px 2px 0px var(--shadow-modal-bolder), 0px 0px 40px 0px var(--shadow-modal-bolder)',
        'rings-brand': '0px 0px 0px 2px var(--focus-ring-brand)',
        'rings-error': '0px 0px 0px 2px var(--focus-ring-error)',
        tabBar: '0px 0px 2px var(--surface)',
        header: '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
        modal: '0px 0px 40px 0px var(--shadow-modal-bolder)',
      },
      ringColor: {
        brand: 'var(--focus-ring-brand)',
        error: 'var(--focus-ring-error)',
      },
      backdropBlur: {},
      backgroundImage: {
        'earn-gradient':
          'linear-gradient(90deg, #3E5CFA 0.12%, #FF469F 49.44%, #FF9915 99.79%)',
        'light-task-gradient':
          'radial-gradient(circle at center, rgba(255, 255, 255, 1) 0%, rgba(255, 255, 255, 0) 100%)',
        'dark-task-gradient':
          'radial-gradi94pigent(circle at center, rgba(39, 40, 44, 1) 0%, rgba(39, 40, 44, 0) 100%)',
        'light-mask':
          'linear-gradient(180deg, rgba(255, 255, 255, 0.60) 0%, rgba(255, 255, 255, 0.97) 84.34%)',
        'dark-mask':
          'linear-gradient(180deg, rgba(45, 46, 51, 0.60) 0%, rgba(39, 40, 44, 0.97) 71.14%)',
        'share-key':
          'linear-gradient(96deg, #3E5CFA 3.78%, #9350E9 14.47%, #C142D4 25.16%, #E237BD 35.85%, #F736A5 46.54%, #FF3E8D 57.23%, #FF4A76 67.93%, #FF5C60 78.62%, #FF6F4C 89.31%, #FF813A 100%)',
        'share-key-hover':
          'linear-gradient(95deg, #3E5CFA 3.71%, #9350E9 32.3%, #C142D4 60.88%, #E237BD 89.47%, #F736A5 118.05%, #FF3E8D 146.64%, #FF4A76 175.23%, #FF5C60 203.81%, #FF6F4C 232.4%, #FF813A 260.98%), linear-gradient(96deg, #3E5CFA 3.78%, #9350E9 14.47%, #C142D4 25.16%, #E237BD 35.85%, #F736A5 46.54%, #FF3E8D 57.23%, #FF4A76 67.93%, #FF5C60 78.62%, #FF6F4C 89.31%, #FF813A 100%)',
        'share-key-press':
          'linear-gradient(95deg, #3E5CFA 3.7%, #9350E9 79.39%, #C142D4 155.08%, #E237BD 230.76%, #F736A5 306.45%, #FF3E8D 382.13%, #FF4A76 457.82%, #FF5C60 533.5%, #FF6F4C 609.19%, #FF813A 684.88%), linear-gradient(96deg, #3E5CFA 3.78%, #9350E9 14.47%, #C142D4 25.16%, #E237BD 35.85%, #F736A5 46.54%, #FF3E8D 57.23%, #FF4A76 67.93%, #FF5C60 78.62%, #FF6F4C 89.31%, #FF813A 100%)',
        'new-tag-gradient':
          'linear-gradient(260deg, #BC0B75 4.58%, #FF0F0F 108.02%)',
        'mobile-light-mask':
          'linear-gradient(240deg, rgba(255, 255, 255, 0.50) 0%, rgba(255, 255, 255, 0.90) 50.52%, #FFF 81.09%)',
        'mobile-dark-mask':
          'linear-gradient(240deg, rgba(39, 40, 44, 0.50) 0%, rgba(39, 40, 44, 0.90) 50.52%, #27282C 81.09%)',
        'stripped-loading':
          'linear-gradient(45deg, #1B35B6 25%, transparent 25%, transparent 50%, #1B35B6 50%, #1B35B6 75%, transparent 75%, transparent)',
      },
      typography: {
        DEFAULT: {
          css: {
            '--tw-prose-body': 'var(--on-surface)',
            '--tw-prose-invert-body': 'var(--on-surface)',
            pre: {
              'border-radius': 0,
            },
          },
        },
      },
      borderRadius: {
        '3xl': '1.25rem',
        '4xl': '1.5rem',
      },
      aspectRatio: {
        '4/3': '4 / 3',
        '3/2': '3 / 2',
      },
    },
  },
};

export const antdToken = {
  buttonRadius: 9999,
};
